### ISSUE TITLE
Remove F-statistics

### ISSUE THREAD

**Issue by trangdata** [insilico/stir#3]
I suggest we remove the computation of the F-statistics in [stir.R](https://github.com/insilico/STIR/blob/master/R/stir.R). The F-test is not appropriate for STIR because we need t-test for one-tailed.

Recall: STIR uses one-tailed t-tests because we want to see how "positive" the mean difference between the miss and hit vector. A good feature that perfectly discriminates the two groups well would have a miss vector of positive values and hit vector of 0 (there is no difference in the value of that feature within one group). Therefore, negative STIR values imply noisy features.

We will have to think more about multi-outcome problems. @brett-mckinney is likely already developing solution to this, but perhaps combining all the miss of different groups into one miss vector?

**Comment by brett-mckinney** [comment]
Excellent point. AOV will lead to increased false positives due to directionality of effects. I don't see where we have used aov in STIR (only t-test), so removing aov should not break any code. 

I do have a couple solutions for multi-state outcomes in the next-generation STIR. The current implementation will do multi-state similar to the way you describe. Implementing a state-specific solution has not been a priority because I don't have a lot of multi-state data that needs to be analyzed. Higher priorities have been numeric outcomes and covariate adjustment, which are implemented.

**Comment by trang1618** [comment]
OK I'll submit a PR.

Is the implementation for numeric outcomes in glmSTIR? I just now saw the repo. Nice work!

**Comment by brett-mckinney** [comment]
Thanks! Yes, numeric outcome and covariate adjustment are in glmSTIR. Case-control outcomes are a special case of glmSTIR. There is also a naive glment version of STIR.

**Comment by trang1618** [comment]
Issue addressed [here](https://github.com/insilico/STIR/commit/d9c77bf02c423b6771fe32b47485536c11f36cbb).
